name: Run Selenium Monitor

on:
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Run Selenium script and Restart Timer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Запуск виртуального дисплея..."
          Xvfb :99 -screen 0 1920x1080x16 & export DISPLAY=:99

          echo "Проверка доступности сайта..."
          python -c "import requests; requests.get('https://1wzjvm.top/casino/play/1play_1play_luckyjet', timeout=10)"

          echo "Запуск Python-скрипта и таймера для перезагрузки..."
          python lucky_parc.py &
          SCRIPT_PID=$!

          # Запускаем таймер на 5 часов 50 минут
          sleep $((5*3600 + 50*60))

          echo "Таймер завершён. Завершаем Python-скрипт..."
          kill $SCRIPT_PID || echo "Скрипт уже завершён."

          echo "Перезапуск Workflow..."
          gh workflow run "Run Selenium Monitor"

          echo "Workflow завершён."
